---
stages:
  - name: Build
    inputs:
      - type: git
        branch: master
    triggers:
      - type: commit
    jobs:
      - name: Build
        type: builder
        script: |-
          #!/bin/bash
          # The default Node.js version is 0.10.40
          # To use Node.js 0.10.48, uncomment the following line:
          #export PATH=/opt/IBM/node-v0.10.48/bin:$PATH
          # To use Node.js 0.12.7, uncomment the following line:
          #export PATH=/opt/IBM/node-v0.12/bin:$PATH
          # To use Node.js 4.4.5, uncomment the following line:
          #export PATH=/opt/IBM/node-v4.4.5/bin:$PATH
          # To use Node.js 6.7.0, uncomment the following line:
          export PATH=/opt/IBM/node-v6.7.0/bin:$PATH

          npm install

  - name: Deploy
    inputs:
      - type: job
        stage: Build
        job: Build
    triggers:
      - type: stage
    jobs:
      - name: dev
        type: deployer
        script: |-
          #!/bin/bash

          curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx
          ./cf push "${CF_APP}" --var VISUAL_RECOGNITION_IAM_APIKEY="${VISUAL_RECOGNITION_IAM_APIKEY}"

        target:
          region_id: ${CF_REGION_ID}
          organization: ${CF_ORGANIZATION}
          space: ${CF_SPACE}
          application: ${CF_APP}
          api_key: ${API_KEY}